import AppointmentList from './Appointment/AppointmentList'
import AppointmentListVideo from './Appointment/AppointmentListVideo'
import LoadingScreen from './Loading'
import PreLabor from './ExamResult/ PreLabor'
import Internal from './ExamResult/Internal'
import Gynaecological from './ExamResult/Gynaecological'
import AntenatalCare from './ExamResult/AntenatalCare'
import Breasts from './ExamResult/Breasts'
import Header from './Header'
import TabbarIcon from './TabbarIcon'
import ButtonText from './ButtonText'
export {Header,AppointmentList,AppointmentListVideo,LoadingScreen,PreLabor,Internal,Gynaecological,AntenatalCare,Breasts,TabbarIcon,ButtonText}